name: Deploy Next.js application

on:
  push:
    branches:
      - deploy-client
    paths:
      - "client/**"
      - ".github/workflows/deploy_client.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL}}" >> .env
      - name: Build docker image
        run: docker build -t bhavi1334/nextjs-app ./client
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Publish image to docker hub
        run: docker push bhavi1334/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull bhavi1334/nextjs-app:latest
      - name: Delete old container
        run: docker rm -f nextjs-app-container
      - name: Run docker container
        run: docker run -d -p 8000:8000 --name nextjs-app-container bhavi1334/nextjs-app
